#!/bin/bash
awk ' $1!="not" || $1!="The" || $1!="in" || $1!="with" || $1!="and" || $1!="of" || $1!="as" || $1!="are" || $1!="to" || $1!="A" || $1!="An" || $1!="is" || $1!="for" || $1!="or" {print}' results.txt

